name: Webapp docker build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASS
        docker build . --file docker/Dockerfile --tag vedantkau/random-datagen-webapp:no_limits
        docker push vedantkau/random-datagen-webapp:no_limits
        docker logout
        echo Done!!
      
